<?php

use Illuminate\Database\Seeder;

class CarsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cars')->delete();
        
        \DB::table('cars')->insert(array (
            0 => 
            array (
                'id' => 1,
                'vin_number' => 'ADIJOW129380EIO',
                'imported_vin_number' => NULL,
                'kind_cd' => 1,
                'fueltype_cd' => 61,
                'engine_cd' => NULL,
                'transmission_cd' => 75,
                'drivetype_cd' => NULL,
                'interior_color_cd' => 1150,
                'exterior_color_cd' => 1150,
                'year' => NULL,
                'registration_date' => NULL,
                'type_cd' => NULL,
                'usage_cd' => NULL,
                'passenger' => 5,
                'output' => '190ps/4000rpm',
                'fuel_consumption' => '14.0',
                'created_at' => '2017-06-09 06:59:50',
                'models_id' => 329,
                'brands_id' => 1,
                'grades_id' => 139,
                'updated_at' => '2017-06-14 18:00:46',
                'details_id' => 138,
            ),
            1 => 
            array (
                'id' => 2,
                'vin_number' => 'FJOIWJOIWJE1987',
                'imported_vin_number' => NULL,
                'kind_cd' => 1,
                'fueltype_cd' => 61,
                'engine_cd' => NULL,
                'transmission_cd' => 75,
                'drivetype_cd' => NULL,
                'interior_color_cd' => 1150,
                'exterior_color_cd' => 1150,
                'year' => NULL,
                'registration_date' => NULL,
                'type_cd' => NULL,
                'usage_cd' => NULL,
                'passenger' => 5,
                'output' => '190ps/4000rpm',
                'fuel_consumption' => '14.0',
                'created_at' => '2017-06-09 06:59:50',
                'models_id' => 329,
                'brands_id' => 1,
                'grades_id' => 139,
                'updated_at' => '2017-06-14 18:00:46',
                'details_id' => 138,
            ),
            2 => 
            array (
                'id' => 3,
                'vin_number' => 'FHJOWIJOE810293',
                'imported_vin_number' => NULL,
                'kind_cd' => 1,
                'fueltype_cd' => 61,
                'engine_cd' => NULL,
                'transmission_cd' => 75,
                'drivetype_cd' => NULL,
                'interior_color_cd' => 1150,
                'exterior_color_cd' => 1150,
                'year' => NULL,
                'registration_date' => NULL,
                'type_cd' => NULL,
                'usage_cd' => NULL,
                'passenger' => 5,
                'output' => '190ps/4000rpm',
                'fuel_consumption' => '14.0',
                'created_at' => '2017-06-09 06:59:50',
                'models_id' => 329,
                'brands_id' => 1,
                'grades_id' => 139,
                'updated_at' => '2017-06-14 18:00:46',
                'details_id' => 138,
            ),
            3 => 
            array (
                'id' => 4,
                'vin_number' => '1219278JFNOIERO',
                'imported_vin_number' => NULL,
                'kind_cd' => 1,
                'fueltype_cd' => 61,
                'engine_cd' => NULL,
                'transmission_cd' => 75,
                'drivetype_cd' => NULL,
                'interior_color_cd' => 1150,
                'exterior_color_cd' => 1150,
                'year' => NULL,
                'registration_date' => NULL,
                'type_cd' => NULL,
                'usage_cd' => NULL,
                'passenger' => 5,
                'output' => '190ps/4000rpm',
                'fuel_consumption' => '14.0',
                'created_at' => '2017-06-09 06:59:50',
                'models_id' => 329,
                'brands_id' => 1,
                'grades_id' => 139,
                'updated_at' => '2017-06-14 18:00:46',
                'details_id' => 138,
            ),
            4 => 
            array (
                'id' => 5,
                'vin_number' => '128FJEH79238478',
                'imported_vin_number' => NULL,
                'kind_cd' => 1,
                'fueltype_cd' => 61,
                'engine_cd' => NULL,
                'transmission_cd' => 75,
                'drivetype_cd' => NULL,
                'interior_color_cd' => 1150,
                'exterior_color_cd' => 1150,
                'year' => NULL,
                'registration_date' => NULL,
                'type_cd' => NULL,
                'usage_cd' => NULL,
                'passenger' => 5,
                'output' => '190ps/4000rpm',
                'fuel_consumption' => '14.0',
                'created_at' => '2017-06-09 06:59:50',
                'models_id' => 329,
                'brands_id' => 1,
                'grades_id' => 139,
                'updated_at' => '2017-06-14 18:00:46',
                'details_id' => 138,
            ),
            5 => 
            array (
                'id' => 6,
                'vin_number' => 'OFIJFOEIWJ97942',
                'imported_vin_number' => NULL,
                'kind_cd' => 1,
                'fueltype_cd' => 61,
                'engine_cd' => NULL,
                'transmission_cd' => 75,
                'drivetype_cd' => NULL,
                'interior_color_cd' => 1150,
                'exterior_color_cd' => 1150,
                'year' => NULL,
                'registration_date' => NULL,
                'type_cd' => NULL,
                'usage_cd' => NULL,
                'passenger' => 5,
                'output' => '190ps/4000rpm',
                'fuel_consumption' => '14.0',
                'created_at' => '2017-06-09 06:59:50',
                'models_id' => 329,
                'brands_id' => 1,
                'grades_id' => 139,
                'updated_at' => '2017-06-14 18:00:46',
                'details_id' => 138,
            ),
            6 => 
            array (
                'id' => 7,
                'vin_number' => '128309182319283',
                'imported_vin_number' => NULL,
                'kind_cd' => 1,
                'fueltype_cd' => 61,
                'engine_cd' => NULL,
                'transmission_cd' => 75,
                'drivetype_cd' => NULL,
                'interior_color_cd' => 1150,
                'exterior_color_cd' => 1150,
                'year' => NULL,
                'registration_date' => NULL,
                'type_cd' => NULL,
                'usage_cd' => NULL,
                'passenger' => 5,
                'output' => '190ps/4000rpm',
                'fuel_consumption' => '14.0',
                'created_at' => '2017-06-09 06:59:50',
                'models_id' => 329,
                'brands_id' => 1,
                'grades_id' => 139,
                'updated_at' => '2017-06-14 18:00:46',
                'details_id' => 138,
            ),
            7 => 
            array (
                'id' => 8,
                'vin_number' => '345345234512323',
                'imported_vin_number' => NULL,
                'kind_cd' => 1,
                'fueltype_cd' => 61,
                'engine_cd' => NULL,
                'transmission_cd' => 75,
                'drivetype_cd' => NULL,
                'interior_color_cd' => 1150,
                'exterior_color_cd' => 1150,
                'year' => NULL,
                'registration_date' => NULL,
                'type_cd' => NULL,
                'usage_cd' => NULL,
                'passenger' => 5,
                'output' => '190ps/4000rpm',
                'fuel_consumption' => '14.0',
                'created_at' => '2017-06-09 06:59:50',
                'models_id' => 329,
                'brands_id' => 1,
                'grades_id' => 139,
                'updated_at' => '2017-06-14 18:00:46',
                'details_id' => 138,
            ),
            8 => 
            array (
                'id' => 9,
                'vin_number' => '29392HHFIEUWH79',
                'imported_vin_number' => NULL,
                'kind_cd' => 1,
                'fueltype_cd' => 61,
                'engine_cd' => NULL,
                'transmission_cd' => 75,
                'drivetype_cd' => NULL,
                'interior_color_cd' => 1150,
                'exterior_color_cd' => 1150,
                'year' => NULL,
                'registration_date' => NULL,
                'type_cd' => NULL,
                'usage_cd' => NULL,
                'passenger' => 5,
                'output' => '190ps/4000rpm',
                'fuel_consumption' => '14.0',
                'created_at' => '2017-06-09 06:59:50',
                'models_id' => 329,
                'brands_id' => 1,
                'grades_id' => 139,
                'updated_at' => '2017-06-14 18:00:46',
                'details_id' => 138,
            ),
            9 => 
            array (
                'id' => 10,
                'vin_number' => '293784289347923',
                'imported_vin_number' => NULL,
                'kind_cd' => 1,
                'fueltype_cd' => 61,
                'engine_cd' => NULL,
                'transmission_cd' => 75,
                'drivetype_cd' => NULL,
                'interior_color_cd' => 1150,
                'exterior_color_cd' => 1150,
                'year' => NULL,
                'registration_date' => NULL,
                'type_cd' => NULL,
                'usage_cd' => NULL,
                'passenger' => 5,
                'output' => '190ps/4000rpm',
                'fuel_consumption' => '14.0',
                'created_at' => '2017-06-09 06:59:50',
                'models_id' => 329,
                'brands_id' => 1,
                'grades_id' => 139,
                'updated_at' => '2017-06-14 18:00:46',
                'details_id' => 138,
            ),
            10 => 
            array (
                'id' => 11,
                'vin_number' => 'IUHFIEWIU123123',
                'imported_vin_number' => NULL,
                'kind_cd' => 1,
                'fueltype_cd' => 61,
                'engine_cd' => NULL,
                'transmission_cd' => 75,
                'drivetype_cd' => NULL,
                'interior_color_cd' => 1150,
                'exterior_color_cd' => 1150,
                'year' => NULL,
                'registration_date' => NULL,
                'type_cd' => NULL,
                'usage_cd' => NULL,
                'passenger' => 5,
                'output' => '190ps/4000rpm',
                'fuel_consumption' => '14.0',
                'created_at' => '2017-06-09 06:59:50',
                'models_id' => 329,
                'brands_id' => 1,
                'grades_id' => 139,
                'updated_at' => '2017-06-14 18:00:46',
                'details_id' => 138,
            ),
            11 => 
            array (
                'id' => 12,
                'vin_number' => '1978928374IHIFU',
                'imported_vin_number' => NULL,
                'kind_cd' => 1,
                'fueltype_cd' => 61,
                'engine_cd' => NULL,
                'transmission_cd' => 75,
                'drivetype_cd' => NULL,
                'interior_color_cd' => 1150,
                'exterior_color_cd' => 1150,
                'year' => NULL,
                'registration_date' => NULL,
                'type_cd' => NULL,
                'usage_cd' => NULL,
                'passenger' => 5,
                'output' => '190ps/4000rpm',
                'fuel_consumption' => '14.0',
                'created_at' => '2017-06-09 06:59:50',
                'models_id' => 329,
                'brands_id' => 1,
                'grades_id' => 139,
                'updated_at' => '2017-06-14 18:00:46',
                'details_id' => 138,
            ),
            12 => 
            array (
                'id' => 13,
                'vin_number' => 'IHFUEIWHUH92734',
                'imported_vin_number' => NULL,
                'kind_cd' => 1,
                'fueltype_cd' => 61,
                'engine_cd' => NULL,
                'transmission_cd' => 75,
                'drivetype_cd' => NULL,
                'interior_color_cd' => 1150,
                'exterior_color_cd' => 1150,
                'year' => NULL,
                'registration_date' => NULL,
                'type_cd' => NULL,
                'usage_cd' => NULL,
                'passenger' => 5,
                'output' => '190ps/4000rpm',
                'fuel_consumption' => '14.0',
                'created_at' => '2017-06-09 06:59:50',
                'models_id' => 329,
                'brands_id' => 1,
                'grades_id' => 139,
                'updated_at' => '2017-06-14 18:00:46',
                'details_id' => 138,
            ),
            13 => 
            array (
                'id' => 14,
                'vin_number' => 'FJOIJWOEI928374',
                'imported_vin_number' => NULL,
                'kind_cd' => 1,
                'fueltype_cd' => 61,
                'engine_cd' => NULL,
                'transmission_cd' => 75,
                'drivetype_cd' => NULL,
                'interior_color_cd' => 1150,
                'exterior_color_cd' => 1150,
                'year' => NULL,
                'registration_date' => NULL,
                'type_cd' => NULL,
                'usage_cd' => NULL,
                'passenger' => 5,
                'output' => '190ps/4000rpm',
                'fuel_consumption' => '14.0',
                'created_at' => '2017-06-09 06:59:50',
                'models_id' => 329,
                'brands_id' => 1,
                'grades_id' => 139,
                'updated_at' => '2017-06-14 18:00:46',
                'details_id' => 138,
            ),
        ));
        
        
    }
}