<?php

/**
 * Created by PhpStorm.
 * User: dev
 * Date: 2017. 5. 29.
 * Time: PM 5:58
 */
use Illuminate\Database\Seeder;
class ModelsSeeder extends Seeder
{
    public function run(){
//        echo DB::table('brands')->where('name', '쉐보레')->first()->id;exit;

        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '1007']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '107']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '알파로메오')->first()->id,'name' =>  '147']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '알파로메오')->first()->id,'name' =>  '156']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '알파로메오')->first()->id,'name' =>  '156GTA']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '알파로메오')->first()->id,'name' =>  '159']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '알파로메오')->first()->id,'name' =>  '164']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '알파로메오')->first()->id,'name' =>  '166']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  '190E 클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'BMW')->first()->id,'name' =>  '1시리즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마쯔다')->first()->id,'name' =>  '2 (데미오)']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '로터스')->first()->id,'name' =>  '2-일레븐']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '크라이슬러')->first()->id,'name' =>  '200']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '2008']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '205']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '206']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '207']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '208']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '로버')->first()->id,'name' =>  '216']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  '250 GTO']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '시트로엥')->first()->id,'name' =>  '2CV']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'BMW')->first()->id,'name' =>  '2시리즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마쯔다')->first()->id,'name' =>  '3 (스피드 악셀라 )']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  '300']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쓰비시')->first()->id,'name' =>  '3000GT']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '3008']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '크라이슬러')->first()->id,'name' =>  '300C']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '크라이슬러')->first()->id,'name' =>  '300M']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '306']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '307']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '308']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마세라티')->first()->id,'name' =>  '3200 GT']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '로터스')->first()->id,'name' =>  '340']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  '348']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포르쉐')->first()->id,'name' =>  '356']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  '360']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'BMW')->first()->id,'name' =>  '3시리즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '405']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '406']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '407']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마세라티')->first()->id,'name' =>  '4200 GT']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  '456']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  '458']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  '488']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '알파로메오')->first()->id,'name' =>  '4C']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '4러너']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'BMW')->first()->id,'name' =>  '4시리즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마쯔다')->first()->id,'name' =>  '5']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '피아트')->first()->id,'name' =>  '500']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '5008']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '505']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '508']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  '512M']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  '512TR']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  '550']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '맥라렌')->first()->id,'name' =>  '570S']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  '575M']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  '599']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'BMW')->first()->id,'name' =>  '5시리즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마쯔다')->first()->id,'name' =>  '6 (아텐자)']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '피아트')->first()->id,'name' =>  '600']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '604']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '605']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '607']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  '612']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '맥라렌')->first()->id,'name' =>  '650S']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '맥라렌')->first()->id,'name' =>  '675LT']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'BMW')->first()->id,'name' =>  '6시리즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포르쉐')->first()->id,'name' =>  '718']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '로버')->first()->id,'name' =>  '75']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'BMW')->first()->id,'name' =>  '7시리즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '806']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  '807']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '볼보')->first()->id,'name' =>  '850']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '올즈모빌')->first()->id,'name' =>  '88LSS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'BMW')->first()->id,'name' =>  '8시리즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '사브')->first()->id,'name' =>  '900']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '사브')->first()->id,'name' =>  '9000']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포르쉐')->first()->id,'name' =>  '911']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '볼보')->first()->id,'name' =>  '940']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '사브')->first()->id,'name' =>  '9월 3일']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '사브')->first()->id,'name' =>  '9월 5일']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '아우디')->first()->id,'name' =>  'A1']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '아우디')->first()->id,'name' =>  'A3']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '아우디')->first()->id,'name' =>  'A4']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '아우디')->first()->id,'name' =>  'A5']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '아우디')->first()->id,'name' =>  'A6']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '아우디')->first()->id,'name' =>  'A7']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '아우디')->first()->id,'name' =>  'A8']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'AMG GT']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '캐딜락')->first()->id,'name' =>  'ATS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마쯔다')->first()->id,'name' =>  'AZ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'A클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '캐딜락')->first()->id,'name' =>  'BLS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'B클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '볼보')->first()->id,'name' =>  'C']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  'C/K 1500']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스파이커')->first()->id,'name' =>  'C8']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  'CC']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '코닉세크')->first()->id,'name' =>  'CCR']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '코닉세크')->first()->id,'name' =>  'CCX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '코닉세크')->first()->id,'name' =>  'CCXR']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '북기은상')->first()->id,'name' =>  'CK ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '어큐라')->first()->id,'name' =>  'CL']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'CLA클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'CLK']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'CLS클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'CL클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  'CR-V']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  'CR-Z']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  'CRX 델솔']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '렉서스')->first()->id,'name' =>  'CT']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '캐딜락')->first()->id,'name' =>  'CT6']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '캐딜락')->first()->id,'name' =>  'CTS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마쯔다')->first()->id,'name' =>  'CX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'C클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '애스턴마틴')->first()->id,'name' =>  'DB']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '애스턴마틴')->first()->id,'name' =>  'DBS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '시트로엥')->first()->id,'name' =>  'DS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '캐딜락')->first()->id,'name' =>  'DTS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  'E-시리즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '제네시스')->first()->id,'name' =>  'EQ900 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '렉서스')->first()->id,'name' =>  'ES']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '인피니티')->first()->id,'name' =>  'EX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  'Expert Tepee']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'E클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  'F-시리즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  'F12 베를리네타']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  'F355']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  'F40']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  'F430']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  'FF']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  'FJ크루져']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쓰비시')->first()->id,'name' =>  'FTO']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '오스틴')->first()->id,'name' =>  'FX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '재규어')->first()->id,'name' =>  'F타입']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '재규어')->first()->id,'name' =>  'F페이스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '인피니티')->first()->id,'name' =>  'G']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  'G2X']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '제네시스')->first()->id,'name' =>  'G80 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'GLA클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'GLC클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'GLE클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'GLK클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'GLS클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'GL클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '렉서스')->first()->id,'name' =>  'GS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  'GT']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  'GTC4 루쏘']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쓰비시')->first()->id,'name' =>  'GTO']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  'GTR']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '알파로메오')->first()->id,'name' =>  'GTV']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '렉서스')->first()->id,'name' =>  'GX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'G클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '허머')->first()->id,'name' =>  'H1 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '허머')->first()->id,'name' =>  'H2 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '허머')->first()->id,'name' =>  'H2 SUT ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '허머')->first()->id,'name' =>  'H3 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '허머')->first()->id,'name' =>  'H3T ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  'HHR']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '어큐라')->first()->id,'name' =>  'INTEGRA']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  'IQ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '렉서스')->first()->id,'name' =>  'IS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '인피니티')->first()->id,'name' =>  'JX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  'K3']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  'K5']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  'K7']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  'K9']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쓰비시')->first()->id,'name' =>  'L200']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '크라이슬러')->first()->id,'name' =>  'LHS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '렉서스')->first()->id,'name' =>  'LS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '렉서스')->first()->id,'name' =>  'LX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '인피니티')->first()->id,'name' =>  'M']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마세라티')->first()->id,'name' =>  'MC 12']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쯔오카')->first()->id,'name' =>  'MC-1']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '어큐라')->first()->id,'name' =>  'MDX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '로버')->first()->id,'name' =>  'MGF ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '링컨')->first()->id,'name' =>  'MKC']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '링컨')->first()->id,'name' =>  'MKS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '링컨')->first()->id,'name' =>  'MKT']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '링컨')->first()->id,'name' =>  'MKX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '링컨')->first()->id,'name' =>  'MKZ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '맥라렌')->first()->id,'name' =>  'MP4-12C']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마쯔다')->first()->id,'name' =>  'MPV']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  'MR']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마쯔다')->first()->id,'name' =>  'MX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'BMW')->first()->id,'name' =>  'M시리즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'M클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  'N-BOX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  'N-ONE']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  'NSX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  'NV밴']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '렉서스')->first()->id,'name' =>  'NX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '크라이슬러')->first()->id,'name' =>  'PT크루저']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  'Parter Tepee']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '인피니티')->first()->id,'name' =>  'Q']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '아우디')->first()->id,'name' =>  'Q3']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '아우디')->first()->id,'name' =>  'Q5']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '아우디')->first()->id,'name' =>  'Q7']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노삼성')->first()->id,'name' =>  'QM3']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노삼성')->first()->id,'name' =>  'QM5']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노삼성')->first()->id,'name' =>  'QM6']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '인피니티')->first()->id,'name' =>  'QX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스카니아')->first()->id,'name' =>  'R470']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '아우디')->first()->id,'name' =>  'R8']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '렉서스')->first()->id,'name' =>  'RC']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '푸조')->first()->id,'name' =>  'RCZ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '어큐라')->first()->id,'name' =>  'RDX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '어큐라')->first()->id,'name' =>  'RL']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '아우디')->first()->id,'name' =>  'RS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '어큐라')->first()->id,'name' =>  'RSX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쓰비시')->first()->id,'name' =>  'RVR']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '렉서스')->first()->id,'name' =>  'RX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'R클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '볼보')->first()->id,'name' =>  'S']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  'S-MAX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  'S10 픽업']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  'S2000']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  'S660']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '렉서스')->first()->id,'name' =>  'SC']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'SEC']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'SEL']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'SL']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'SLC클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'SLK']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'SLR']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'SLS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노삼성')->first()->id,'name' =>  'SM3']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노삼성')->first()->id,'name' =>  'SM5']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노삼성')->first()->id,'name' =>  'SM6']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노삼성')->first()->id,'name' =>  'SM7']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '아우디')->first()->id,'name' =>  'SQ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '캐딜락')->first()->id,'name' =>  'SRX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  'SSR']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '캐딜락')->first()->id,'name' =>  'STS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  'SX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'S클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '재규어')->first()->id,'name' =>  'S타입']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '어큐라')->first()->id,'name' =>  'TL']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '어큐라')->first()->id,'name' =>  'TSX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '아우디')->first()->id,'name' =>  'TT']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '홀덴')->first()->id,'name' =>  'UTE']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '볼보')->first()->id,'name' =>  'V']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '애스턴마틴')->first()->id,'name' =>  'Vantage']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  'V클래스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  'X-트렉']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '볼보')->first()->id,'name' =>  'XC']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '재규어')->first()->id,'name' =>  'XE']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '재규어')->first()->id,'name' =>  'XF']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '재규어')->first()->id,'name' =>  'XJ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '재규어')->first()->id,'name' =>  'XJ6']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '재규어')->first()->id,'name' =>  'XJ8']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '재규어')->first()->id,'name' =>  'XJR']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '재규어')->first()->id,'name' =>  'XJS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '재규어')->first()->id,'name' =>  'XK']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '캐딜락')->first()->id,'name' =>  'XLR']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '캐딜락')->first()->id,'name' =>  'XT5']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'BMW')->first()->id,'name' =>  'X시리즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '재규어')->first()->id,'name' =>  'X타입']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  'Z']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '어큐라')->first()->id,'name' =>  'ZDX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'BMW')->first()->id,'name' =>  'Z시리즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  'bB']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '인피니티')->first()->id,'name' =>  'i']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  'i20']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'BMW')->first()->id,'name' =>  'i3']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  'i30']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  'i40']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'BMW')->first()->id,'name' =>  'i8']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쯔오카')->first()->id,'name' =>  '가류']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '람보르기니')->first()->id,'name' =>  '가야르도']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '갤로퍼']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '롤스로이스')->first()->id,'name' =>  '고스트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '골프']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '그라나다']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마세라티')->first()->id,'name' =>  '그란카브리오']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마세라티')->first()->id,'name' =>  '그란투리스모']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폰티악')->first()->id,'name' =>  '그랑프리']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스즈키')->first()->id,'name' =>  '그랜드 비타라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '머큐리')->first()->id,'name' =>  '그랜드마퀴스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폰티악')->first()->id,'name' =>  '그랜드엠']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '그랜버드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '그랜져']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '그레이스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마세라티')->first()->id,'name' =>  '기블리']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쯔오카')->first()->id,'name' =>  '기타']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '링컨')->first()->id,'name' =>  '네비게이터']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '넥시아']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '노아']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '누비라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쯔오카')->first()->id,'name' =>  '누에라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '랜드로버')->first()->id,'name' =>  '뉴 레인지로버 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '랜드로버')->first()->id,'name' =>  '뉴 레인지로버 스포츠 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '랜드로버')->first()->id,'name' =>  '뉴프리랜더 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '니로']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닷지')->first()->id,'name' =>  '니트로']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '다마스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '다이너스티']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '재규어')->first()->id,'name' =>  '다임러']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닷지')->first()->id,'name' =>  '다코타 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  '댓츠']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '롤스로이스')->first()->id,'name' =>  '던']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '란치아')->first()->id,'name' =>  '데드라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '란치아')->first()->id,'name' =>  '델타']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쯔오카')->first()->id,'name' =>  '도오라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '도요타 86']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닷지')->first()->id,'name' =>  '듀란고']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '캐딜락')->first()->id,'name' =>  '드빌']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '랜드로버')->first()->id,'name' =>  '디스커버리 스포츠 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '랜드로버')->first()->id,'name' =>  '디스커버리1 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '랜드로버')->first()->id,'name' =>  '디스커버리2 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '랜드로버')->first()->id,'name' =>  '디스커버리3 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '랜드로버')->first()->id,'name' =>  '디스커버리4 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '람보르기니')->first()->id,'name' =>  '디아블로']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '랜드로버')->first()->id,'name' =>  '디펜더 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노')->first()->id,'name' =>  '라구나 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '라노스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '라보']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '라브4']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '라비타']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쯔오카')->first()->id,'name' =>  '라세드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '라세티']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '라우탄']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '라이노']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '란치아')->first()->id,'name' =>  '라이브라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '피스커')->first()->id,'name' =>  '라티고 CS']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '애스턴마틴')->first()->id,'name' =>  '라피드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '랜드크루저']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쓰비시')->first()->id,'name' =>  '랜서']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쓰비시')->first()->id,'name' =>  '랜서에볼루션']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닷지')->first()->id,'name' =>  '램 밴']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닷지')->first()->id,'name' =>  '램 픽업']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '지프')->first()->id,'name' =>  '랭글러']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스바루')->first()->id,'name' =>  '레가시']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '레간자']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '지프')->first()->id,'name' =>  '레니게이드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '람보르기니')->first()->id,'name' =>  '레벤톤']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '레이']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '롤스로이스')->first()->id,'name' =>  '레이스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '레인져']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '랜드로버')->first()->id,'name' =>  '레인지로버 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '랜드로버')->first()->id,'name' =>  '레인지로버 스포츠 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '랜드로버')->first()->id,'name' =>  '레인지로버 이보크 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  '레전드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '레조']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '레토나']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쌍용')->first()->id,'name' =>  '렉스턴']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '로그']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '이스즈')->first()->id,'name' =>  '로데오']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '비이스만')->first()->id,'name' =>  '로드스터']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쌍용')->first()->id,'name' =>  '로디우스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '로얄살롱']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '로체']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '록스타']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '르망']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마세라티')->first()->id,'name' =>  '르반떼']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '뷰익')->first()->id,'name' =>  '르사블']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '뷰익')->first()->id,'name' =>  '리갈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '지프')->first()->id,'name' =>  '리버티']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '리베로']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '뷰익')->first()->id,'name' =>  '리비에라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '리알타']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '리오']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  '리지라인']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '마르샤']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '머큐리')->first()->id,'name' =>  '마리너']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '머큐리')->first()->id,'name' =>  '마운티니어']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  '마이바흐']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '마이크로버스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '마이티']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '마치']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포르쉐')->first()->id,'name' =>  '마칸']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '다이하쓰')->first()->id,'name' =>  '마테리아']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '마티즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '말리부']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '매그너스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닷지')->first()->id,'name' =>  '매그넘']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '매트릭스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '맥스크루즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '맥시마']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '맵시']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '맵시나']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '머스탱']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노')->first()->id,'name' =>  '메간 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '홀덴')->first()->id,'name' =>  '모나로']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '모닝']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '테슬라')->first()->id,'name' =>  '모델 S']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노')->first()->id,'name' =>  '모뒤스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '모하비']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '몬데오']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '머큐리')->first()->id,'name' =>  '몬테고']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쓰비시')->first()->id,'name' =>  '몬테로']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '무라노']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '람보르기니')->first()->id,'name' =>  '무르시엘라고']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쌍용')->first()->id,'name' =>  '무쏘']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '이스즈')->first()->id,'name' =>  '뮤']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤틀리')->first()->id,'name' =>  '뮬산']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '로버')->first()->id,'name' =>  '미니']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '다이하쓰')->first()->id,'name' =>  '미라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '머큐리')->first()->id,'name' =>  '미스틱']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '알파로메오')->first()->id,'name' =>  '미토']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '머큐리')->first()->id,'name' =>  '밀란']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '바네트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '피아트')->first()->id,'name' =>  '바르게타']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '홀덴')->first()->id,'name' =>  '바리나']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마세라티')->first()->id,'name' =>  '바이터보']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닷지')->first()->id,'name' =>  '바이퍼']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포르쉐')->first()->id,'name' =>  '박스터']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닷지')->first()->id,'name' =>  '밴']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '애스턴마틴')->first()->id,'name' =>  '뱅퀴시']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '버사(티이다)']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '베라크루즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '베르나']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '베리타스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '베스타']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '부가티')->first()->id,'name' =>  '베이론 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '오펠')->first()->id,'name' =>  '벡트라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '어울림모터스')->first()->id,'name' =>  '벤가리']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '벤자']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'GMC')->first()->id,'name' =>  '벤츄라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤틀리')->first()->id,'name' =>  '벤테이가']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '벤토']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '벨로스터']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노')->first()->id,'name' =>  '벨사티스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '보라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '크라이슬러')->first()->id,'name' =>  '보이저']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '복사']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '복시']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '볼트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '봉고']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '다이하쓰')->first()->id,'name' =>  '분']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '새턴')->first()->id,'name' =>  '뷰 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쯔오카')->first()->id,'name' =>  '뷰트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '알파로메오')->first()->id,'name' =>  '브레라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '브로엄']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '브롱코']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤틀리')->first()->id,'name' =>  '브룩랜즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '브리사']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  '블레이저']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '비스토']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  '비아노']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '크라이슬러')->first()->id,'name' =>  '비전']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '이스즈')->first()->id,'name' =>  '비크로스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '오펠')->first()->id,'name' =>  '비타']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  '비트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '비틀']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '머큐리')->first()->id,'name' =>  '빌리저']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'GMC')->first()->id,'name' =>  '사바나밴']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포톤')->first()->id,'name' =>  '사우바나']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스즈키')->first()->id,'name' =>  '사이드킥']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '사이언']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'GMC')->first()->id,'name' =>  '사파리']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  '서버밴']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노')->first()->id,'name' =>  '세닉']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '세라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '세레스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '크라이슬러')->first()->id,'name' =>  '세브링']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '머큐리')->first()->id,'name' =>  '세이블']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '세콰이어']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '세피아']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '센츄리']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '셀리카']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '셀시오']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '재규어')->first()->id,'name' =>  '소버린']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '소아라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '솔라라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스즈키')->first()->id,'name' =>  '솔리오']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폰티악')->first()->id,'name' =>  '솔스티스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '수퍼살롱']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '수프라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '슈마']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '웨스트필드')->first()->id,'name' =>  '슈퍼세븐']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  '스마트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스즈키')->first()->id,'name' =>  '스위프트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '새턴')->first()->id,'name' =>  '스카이 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '스카이라인']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '뷰익')->first()->id,'name' =>  '스카이락']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '스쿠프']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '스타렉스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '스테이지아']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '홀덴')->first()->id,'name' =>  '스테이츠맨']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '스텔라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '크라이슬러')->first()->id,'name' =>  '스트라투스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '스팅어']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '알파로메오')->first()->id,'name' =>  '스파이더']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '스파크']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '스펙트라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노')->first()->id,'name' =>  '스포츠 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '스포츠트랙']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '스포티지']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤츠')->first()->id,'name' =>  '스프린터']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '오펠')->first()->id,'name' =>  '스피드스터']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '어울림모터스')->first()->id,'name' =>  '스피라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '시로코']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '시마']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  '시빅']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '시에나']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '올즈모빌')->first()->id,'name' =>  '실루엣 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '롤스로이스')->first()->id,'name' =>  '실버 세라프']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '롤스로이스')->first()->id,'name' =>  '실버 스피릿(스퍼)']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  '실버라도 픽업']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '실비아']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '싼타모']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '싼타페']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '썬더버드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '쎄라토']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '쏘나타']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '쏘렌토']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '쏘울']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '쏠라티']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '씨에로']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤틀리')->first()->id,'name' =>  '아르나지']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '아마록']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '아반떼']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  '아발란치']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '아발론']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '아베오']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '람보르기니')->first()->id,'name' =>  '아벤타도르']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '아벨라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '오펠')->first()->id,'name' =>  '아스트라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  '아스트로밴']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '아슬란']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '새턴')->first()->id,'name' =>  '아우라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쓰비시')->first()->id,'name' =>  '아웃랜더']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '새턴')->first()->id,'name' =>  '아웃룩']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스바루')->first()->id,'name' =>  '아웃백']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '아이고']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '아이오닉']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤틀리')->first()->id,'name' =>  '아주어']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '아카디아']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '아토스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '알마다']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '알테자']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스즈키')->first()->id,'name' =>  '알토']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스즈키')->first()->id,'name' =>  '알토라팡']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '알티마']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '알파드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '알페온']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쌍용')->first()->id,'name' =>  '액티언']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '야리스(비츠)']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노삼성')->first()->id,'name' =>  '야무진']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  '어코드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '업']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  '에딕스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '로터스')->first()->id,'name' =>  '에보라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '링컨')->first()->id,'name' =>  '에비에이터']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노')->first()->id,'name' =>  '에스빠스 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '캐딜락')->first()->id,'name' =>  '에스컬레이드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '에스페로']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '로터스')->first()->id,'name' =>  '에스프리']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '에어로']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '에쿠스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '홀덴')->first()->id,'name' =>  '에피카']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '엑센트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '엑셀']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '엑스테라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '로터스')->first()->id,'name' =>  '엑시지']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  '엔초']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '뷰익')->first()->id,'name' =>  '엔클라브']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '엔터프라이즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '엘그란드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '캐딜락')->first()->id,'name' =>  '엘도라도']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '엘란']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '엘란트라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  '엘리먼트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '로터스')->first()->id,'name' =>  '엘리스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  '오딧세이']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '올즈모빌')->first()->id,'name' =>  '오로라 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쯔오카')->first()->id,'name' =>  '오로치']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '오펠')->first()->id,'name' =>  '오메가']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '오피러스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '올란도']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '아우디')->first()->id,'name' =>  '올로드콰트로']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '옵티마']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스즈키')->first()->id,'name' =>  '왜건 R']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '람보르기니')->first()->id,'name' =>  '우라칸']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '다이하쓰')->first()->id,'name' =>  '웨이크']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '위시']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '윈드스타']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '윈스톰']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '윌']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '윙로드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마쯔다')->first()->id,'name' =>  '유노스로드스터']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '유니버스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '로터스')->first()->id,'name' =>  '유로파']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'GMC')->first()->id,'name' =>  '유콘']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '이스케이프']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쌍용')->first()->id,'name' =>  '이스타나']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '이오스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스즈키')->first()->id,'name' =>  '이퀘이터']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쓰비시')->first()->id,'name' =>  '이클립스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '익스페디션']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  '익스프레스밴']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '익스플로러']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  '인사이트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  '인테그라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  '임팔라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '임페리얼']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스바루')->first()->id,'name' =>  '임프레자']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스바루')->first()->id,'name' =>  '임프레자 WRX']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '입섬']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '제네시스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '제타']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '젠트라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '파가니')->first()->id,'name' =>  '존다 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '알파로메오')->first()->id,'name' =>  '줄리에타']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '쥬크']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스즈키')->first()->id,'name' =>  '짐니']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닷지')->first()->id,'name' =>  '차저']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닷지')->first()->id,'name' =>  '챌린저']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '지프')->first()->id,'name' =>  '체로키']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  '체비밴']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쌍용')->first()->id,'name' =>  '체어맨']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '카고']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '카니발']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '오펠')->first()->id,'name' =>  '카데트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포르쉐')->first()->id,'name' =>  '카레라GT']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '카렌스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '카르만기어']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  '카마로']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '카스타']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '카운티']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쌍용')->first()->id,'name' =>  '카이런']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포르쉐')->first()->id,'name' =>  '카이맨']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포르쉐')->first()->id,'name' =>  '카이엔']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '란치아')->first()->id,'name' =>  '카파']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스즈키')->first()->id,'name' =>  '카푸치노']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '홀덴')->first()->id,'name' =>  '카프라이스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '홀덴')->first()->id,'name' =>  '칼라이스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '칼로스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쌍용')->first()->id,'name' =>  '칼리스타']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '크라이슬러')->first()->id,'name' =>  '캐러밴']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '다이하쓰')->first()->id,'name' =>  '캐스트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '캐시카이']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '캐피탈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닷지')->first()->id,'name' =>  '캘리버']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '페라리')->first()->id,'name' =>  '캘리포니아']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '캠리']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기타')->first()->id,'name' =>  '캠핑 트레일러']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  '캠핑카']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '홀덴')->first()->id,'name' =>  '캡티바']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '지프')->first()->id,'name' =>  '커맨더']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미니')->first()->id,'name' =>  '컨트리맨']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '링컨')->first()->id,'name' =>  '컨티넨탈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤틀리')->first()->id,'name' =>  '컨티넨탈 GT']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤틀리')->first()->id,'name' =>  '컨티넨탈 플라잉스퍼']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '지프')->first()->id,'name' =>  '컴패스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스즈키')->first()->id,'name' =>  '케이']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '롤스로이스')->first()->id,'name' =>  '코니쉬']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '코라도']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쌍용')->first()->id,'name' =>  '코란도']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '코러스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '코롤라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '오펠')->first()->id,'name' =>  '코르사']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '홀덴')->first()->id,'name' =>  '코모도어']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '코스모스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '코티나']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '다이하쓰')->first()->id,'name' =>  '코펜']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  '콜로라도']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  '콜벳']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '홀덴')->first()->id,'name' =>  '콤보']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '콤비']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '콩코드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마세라티')->first()->id,'name' =>  '콰트로포르테']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '쿠가']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미니')->first()->id,'name' =>  '쿠퍼']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미니')->first()->id,'name' =>  '쿠페']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '퀘스트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '큐브']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '크라운']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '크레도스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '피아트')->first()->id,'name' =>  '크로마']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  '크로스로드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  '크로스투어']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '크라이슬러')->first()->id,'name' =>  '크로스파이어']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '홀덴')->first()->id,'name' =>  '크루즈']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미니')->first()->id,'name' =>  '클럽맨']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노')->first()->id,'name' =>  '클리오 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '클릭']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '타우너']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '링컨')->first()->id,'name' =>  '타운카']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '타이탄']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '타코마 픽업']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  '타호']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '다이하쓰')->first()->id,'name' =>  '탄토']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '벤틀리')->first()->id,'name' =>  '터보 R']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '사브')->first()->id,'name' =>  '터보-X']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '테라칸']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '란치아')->first()->id,'name' =>  '테마']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '란치아')->first()->id,'name' =>  '테시스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '토러스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '토스카']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '토픽']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '투스카니']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '투싼']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '투아렉']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '툰드라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포톤')->first()->id,'name' =>  '툰랜드 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '트라고']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '피스커')->first()->id,'name' =>  '트라몬토']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '트라제XG']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '트랙스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', 'GM')->first()->id,'name' =>  '트랙커']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폰티악')->first()->id,'name' =>  '트랜스앰']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '트랜짓']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '트럭']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  '트럭밴']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '트레이드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '마쯔다')->first()->id,'name' =>  '트리뷰트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '르노')->first()->id,'name' =>  '트윙고']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '티구안']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '오펠')->first()->id,'name' =>  '티그라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쌍용')->first()->id,'name' =>  '티볼리']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '티뷰론']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '티아나']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '티코']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포르쉐')->first()->id,'name' =>  '파나메라']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '파맥스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '파사트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '파오']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '파이브 헌드레드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폰티악')->first()->id,'name' =>  '파이어버드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  '파일럿']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쓰비시')->first()->id,'name' =>  '파제로']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '뷰익')->first()->id,'name' =>  '파크애비뉴']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '파크타운']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '피아트')->first()->id,'name' =>  '판다 4×4']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '패스파인더']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '지프')->first()->id,'name' =>  '패트리어트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '롤스로이스')->first()->id,'name' =>  '팬텀']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '크라이슬러')->first()->id,'name' =>  '퍼시피카']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '펀 카르고']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미니')->first()->id,'name' =>  '페이스맨']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '페이톤']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '포니']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스바루')->first()->id,'name' =>  '포레스터']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '포르테']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '포커스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '포터']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '포텐샤']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '폭스바겐')->first()->id,'name' =>  '폴로']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '피아트')->first()->id,'name' =>  '푼토']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '퓨전']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '크라이슬러')->first()->id,'name' =>  '프라울러']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '프라이드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '현대')->first()->id,'name' =>  '프레스토']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '프레지오']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '혼다')->first()->id,'name' =>  '프렐류드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '프론티어']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '랜드로버')->first()->id,'name' =>  '프리랜더 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '랜드로버')->first()->id,'name' =>  '프리랜더2 (06년~현제)']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '프리마']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '피아트')->first()->id,'name' =>  '프리몬트']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '포드')->first()->id,'name' =>  '프리스타일']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '프리우스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레/대우')->first()->id,'name' =>  '프린스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '캐딜락')->first()->id,'name' =>  '플리트우드']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기아')->first()->id,'name' =>  '피아트 132']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '쉐보레')->first()->id,'name' =>  '픽업']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '하이랜더']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '하이럭스']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '도요타')->first()->id,'name' =>  '해리어']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스즈키')->first()->id,'name' =>  '허슬러']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '후가']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '파가니')->first()->id,'name' =>  '후에이라 ']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '닛산')->first()->id,'name' =>  '휘가로']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '기타')->first()->id,'name' =>  '희소차량']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '스카니아')->first()->id,'name' =>  '히노']);
        DB::table('models')->insert(['brand_id' => DB::table('brands')->where('name', '미쯔오카')->first()->id,'name' =>  '히미코']);
    }
}