<?php

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(array (
            0 => 
            array (
                'id' => 1,
                'datekey' => '170607',
                'car_number' => '11가1111',
                'cars_id' => 0,
                'garage_id' => 4,
                'item_id' => 1,
                'purchase_id' => 1,
                'engineer_id' => 5,
                'technist_id' => 6,
                'orderer_id' => 2,
                'orderer_name' => 'Daily Jude',
                'orderer_mobile' => '010-2345-2345',
                'registration_file_cd' => 3,
                'mileage' => 100000,
                'open_cd' => 3,
                'verification_id' => NULL,
                'status_cd' => 104,
                'created_at' => '2017-06-09 16:00:57',
                'updated_at' => NULL,
                'diagnose_at' => NULL,
                'diagnosed_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'datekey' => '170607',
                'car_number' => '12나2222',
                'cars_id' => 0,
                'garage_id' => 4,
                'item_id' => 1,
                'purchase_id' => 1,
                'engineer_id' => 5,
                'technist_id' => 6,
                'orderer_id' => 2,
                'orderer_name' => 'Daily Jude',
                'orderer_mobile' => '010-2345-2345',
                'registration_file_cd' => 3,
                'mileage' => 100000,
                'open_cd' => 3,
                'verification_id' => NULL,
                'status_cd' => 105,
                'created_at' => '2017-06-09 16:00:57',
                'updated_at' => '2017-06-13 23:15:50',
                'diagnose_at' => NULL,
                'diagnosed_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'datekey' => '170608',
                'car_number' => '21가1111',
                'cars_id' => 0,
                'garage_id' => 4,
                'item_id' => 1,
                'purchase_id' => 1,
                'engineer_id' => 5,
                'technist_id' => 6,
                'orderer_id' => 2,
                'orderer_name' => 'Daily Jude',
                'orderer_mobile' => '010-2345-2345',
                'registration_file_cd' => 3,
                'mileage' => 100000,
                'open_cd' => 3,
                'verification_id' => NULL,
                'status_cd' => 106,
                'created_at' => '2017-06-09 16:00:57',
                'updated_at' => '2017-06-13 23:15:50',
                'diagnose_at' => NULL,
                'diagnosed_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'datekey' => '170608',
                'car_number' => '22나2222',
                'cars_id' => 0,
                'garage_id' => 4,
                'item_id' => 1,
                'purchase_id' => 1,
                'engineer_id' => 5,
                'technist_id' => 6,
                'orderer_id' => 2,
                'orderer_name' => 'Daily Jude',
                'orderer_mobile' => '010-2345-2345',
                'registration_file_cd' => 3,
                'mileage' => 100000,
                'open_cd' => 3,
                'verification_id' => NULL,
                'status_cd' => 107,
                'created_at' => '2017-06-09 16:00:57',
                'updated_at' => '2017-06-13 23:15:50',
                'diagnose_at' => NULL,
                'diagnosed_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'datekey' => '170609',
                'car_number' => '31가1111',
                'cars_id' => 0,
                'garage_id' => 4,
                'item_id' => 1,
                'purchase_id' => 1,
                'engineer_id' => 5,
                'technist_id' => 6,
                'orderer_id' => 2,
                'orderer_name' => 'Daily Jude',
                'orderer_mobile' => '010-2345-2345',
                'registration_file_cd' => 3,
                'mileage' => 100000,
                'open_cd' => 3,
                'verification_id' => NULL,
                'status_cd' => 104,
                'created_at' => '2017-06-09 16:00:57',
                'updated_at' => NULL,
                'diagnose_at' => NULL,
                'diagnosed_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'datekey' => '170609',
                'car_number' => '32나2222',
                'cars_id' => 0,
                'garage_id' => 4,
                'item_id' => 1,
                'purchase_id' => 1,
                'engineer_id' => 5,
                'technist_id' => 6,
                'orderer_id' => 2,
                'orderer_name' => 'Daily Jude',
                'orderer_mobile' => '010-2345-2345',
                'registration_file_cd' => 3,
                'mileage' => 100000,
                'open_cd' => 3,
                'verification_id' => NULL,
                'status_cd' => 105,
                'created_at' => '2017-06-09 16:00:57',
                'updated_at' => '2017-06-13 23:15:50',
                'diagnose_at' => NULL,
                'diagnosed_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'datekey' => '170610',
                'car_number' => '41가1111',
                'cars_id' => 0,
                'garage_id' => 4,
                'item_id' => 1,
                'purchase_id' => 1,
                'engineer_id' => 5,
                'technist_id' => 6,
                'orderer_id' => 2,
                'orderer_name' => 'Daily Jude',
                'orderer_mobile' => '010-2345-2345',
                'registration_file_cd' => 3,
                'mileage' => 100000,
                'open_cd' => 3,
                'verification_id' => NULL,
                'status_cd' => 106,
                'created_at' => '2017-06-09 16:00:57',
                'updated_at' => '2017-06-13 23:15:50',
                'diagnose_at' => NULL,
                'diagnosed_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'datekey' => '170610',
                'car_number' => '42나2222',
                'cars_id' => 0,
                'garage_id' => 4,
                'item_id' => 1,
                'purchase_id' => 1,
                'engineer_id' => 5,
                'technist_id' => 6,
                'orderer_id' => 2,
                'orderer_name' => 'Daily Jude',
                'orderer_mobile' => '010-2345-2345',
                'registration_file_cd' => 3,
                'mileage' => 100000,
                'open_cd' => 3,
                'verification_id' => NULL,
                'status_cd' => 107,
                'created_at' => '2017-06-09 16:00:57',
                'updated_at' => '2017-06-13 23:15:50',
                'diagnose_at' => NULL,
                'diagnosed_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'datekey' => '170611',
                'car_number' => '51가1111',
                'cars_id' => 0,
                'garage_id' => 4,
                'item_id' => 1,
                'purchase_id' => 1,
                'engineer_id' => 5,
                'technist_id' => 6,
                'orderer_id' => 2,
                'orderer_name' => 'Daily Jude',
                'orderer_mobile' => '010-2345-2345',
                'registration_file_cd' => 3,
                'mileage' => 100000,
                'open_cd' => 3,
                'verification_id' => NULL,
                'status_cd' => 104,
                'created_at' => '2017-06-09 16:00:57',
                'updated_at' => NULL,
                'diagnose_at' => NULL,
                'diagnosed_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'datekey' => '170611',
                'car_number' => '51나2222',
                'cars_id' => 0,
                'garage_id' => 4,
                'item_id' => 1,
                'purchase_id' => 1,
                'engineer_id' => 5,
                'technist_id' => 6,
                'orderer_id' => 2,
                'orderer_name' => 'Daily Jude',
                'orderer_mobile' => '010-2345-2345',
                'registration_file_cd' => 3,
                'mileage' => 100000,
                'open_cd' => 3,
                'verification_id' => NULL,
                'status_cd' => 105,
                'created_at' => '2017-06-09 16:00:57',
                'updated_at' => '2017-06-13 23:15:50',
                'diagnose_at' => NULL,
                'diagnosed_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'datekey' => '170607',
                'car_number' => '61다6666',
                'cars_id' => 0,
                'garage_id' => 4,
                'item_id' => 1,
                'purchase_id' => 1,
                'engineer_id' => 5,
                'technist_id' => 6,
                'orderer_id' => 2,
                'orderer_name' => 'Daily Jude',
                'orderer_mobile' => '010-2345-2345',
                'registration_file_cd' => 3,
                'mileage' => 100000,
                'open_cd' => 3,
                'verification_id' => NULL,
                'status_cd' => 106,
                'created_at' => '2017-06-09 16:00:57',
                'updated_at' => '2017-06-13 23:15:50',
                'diagnose_at' => NULL,
                'diagnosed_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'datekey' => '170607',
                'car_number' => '62다7777',
                'cars_id' => 0,
                'garage_id' => 4,
                'item_id' => 1,
                'purchase_id' => 1,
                'engineer_id' => 5,
                'technist_id' => 6,
                'orderer_id' => 2,
                'orderer_name' => 'Daily Jude',
                'orderer_mobile' => '010-2345-2345',
                'registration_file_cd' => 3,
                'mileage' => 100000,
                'open_cd' => 3,
                'verification_id' => NULL,
                'status_cd' => 107,
                'created_at' => '2017-06-09 16:00:57',
                'updated_at' => '2017-06-13 23:15:50',
                'diagnose_at' => NULL,
                'diagnosed_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'datekey' => '170608',
                'car_number' => '71라7777',
                'cars_id' => 0,
                'garage_id' => 4,
                'item_id' => 1,
                'purchase_id' => 1,
                'engineer_id' => 5,
                'technist_id' => 6,
                'orderer_id' => 2,
                'orderer_name' => 'Daily Jude',
                'orderer_mobile' => '010-2345-2345',
                'registration_file_cd' => 3,
                'mileage' => 100000,
                'open_cd' => 3,
                'verification_id' => NULL,
                'status_cd' => 104,
                'created_at' => '2017-06-09 16:00:57',
                'updated_at' => NULL,
                'diagnose_at' => NULL,
                'diagnosed_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'datekey' => '170608',
                'car_number' => '72라8888',
                'cars_id' => 0,
                'garage_id' => 4,
                'item_id' => 1,
                'purchase_id' => 1,
                'engineer_id' => 5,
                'technist_id' => 6,
                'orderer_id' => 2,
                'orderer_name' => 'Daily Jude',
                'orderer_mobile' => '010-2345-2345',
                'registration_file_cd' => 3,
                'mileage' => 100000,
                'open_cd' => 3,
                'verification_id' => NULL,
                'status_cd' => 105,
                'created_at' => '2017-06-09 16:00:57',
                'updated_at' => '2017-06-13 23:15:50',
                'diagnose_at' => NULL,
                'diagnosed_at' => NULL,
            ),
        ));
        
        
    }
}