image: php:7-fpm
pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -qy git curl libmcrypt-dev mysql-client
          - docker-php-ext-install mcrypt && docker-php-ext-install pdo_mysql
          - composer install
          - export CACHE_DRIVER=redis
          - export SESSION_DRIVER=redis
          - export DB_CONNECTION=mysql
          
definitions:
  services:
    mysql:
      image: mysql
      environment:
        MYSQL_HOST: 'cargumsa.c4afr6fhjklv.ap-northeast-2.rds.amazonaws.com'
        MYSQL_DATABASE: 'chagumsa'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'cargumsa'
        MYSQL_PASSWORD: 'zkrjatk#1010'